### ISSUE TITLE
Support scroll-padding

### ISSUE THREAD

**Issue by powerbuoy** [jonaskuske/smoothscroll-anchor-polyfill#34]
Any chance you could add support for scroll-padding?

**Comment by jonaskuske** [comment]
Yep, sounds very useful – didn't know this property existed!
Will look into it :)

**Comment by kahl-dev** [comment]
Would love to see this happen

**Comment by austincarpenter** [comment]
Any update on this one? I'm assuming this would include scroll-margin too?

**Comment by DavidLindsey0118** [comment]
Chiming in, this would be extremely helpful...running into lots of issues with fixed mobile navigation cutting off the top of sections because the lib does not respect scroll-margin or scroll-padding in CSS

**Comment by jonaskuske** [comment]
Hey, just to give you a quick heads-up:
I'll look into it this week, but can't promise anything as of now, as it might be actually quite complicated to make this happen given the current implementation (which just calls `.scrollIntoView()` and is not concerned with individual scrolls). I have some ideas though, so we'll see!

**Comment by DavidLindsey0118** [comment]
That would be incredible, thank you!

**Comment by DavidLindsey0118** [comment]
To clarify, I'm only seeing this particular issue with the lib on IOS
devices.

**Comment by jonaskuske** [comment]
Nothing new for `scroll-padding`, BUT `scroll-margin` is supported when this lib is used in tandem with seamless-scroll-polyfill: https://github.com/jonaskuske/smoothscroll-anchor-polyfill/issues/51#issuecomment-1063970586

So you can apply a scroll margin to the scrollable/targetable elements (instead of a padding for the scroll container) and avoid the mobile navigation issue:

```css
/* Doesn't work (yet) 👎 */
.scroll-container {
  scroll-padding-top: 100px; /* adjust for fixed navigation */
}

/* Works 👍 */
[id] {
  scroll-margin-top: 100px; /* adjust for fixed navigation */
}
```
